name: LesMarti
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5cbd7'
    - '#94afc4'
    - '#2b2d2c'
    - '#7ca442'
    - '#466123'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
