name: LesMarti
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09134
title: Travel / Documentary/ Lifestyle
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#60c67d'
    - '#757575'
    - '#e3e7e6'
    - '#00c2dd'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
