name: LesMarti
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312926'
    - '#9b8884'
    - '#6e5b57'
    - '#fbfbfb'
    - '#d5d670'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0
purpose: []
