name: LesMarti
favicon: null
layout_spectrum: 0.54886
typography_spectrum: 0.10328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bacedc'
    - '#262626'
    - '#716754'
    - '#ecb50b'
    - '#165567'
  brandStrength: 0.125
  lightness: 0.7768990502227098
  saturation: 0.04857500619255006
  rhythmicContrast: 0.7129385233856738
purpose: []
