name: LesMarti
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#60c67d'
    - '#757575'
    - '#e3e7e6'
    - '#00c2dd'
  brandStrength: 0.125
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
