name: LesMarti Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09134
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99A4B3'
    - '#788799'
    - '#F2F3F2'
    - '#3A4A64'
  brandStrength: 0.3125
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.8847073
purpose: []
