title: Travel / Documentary/ Lifestyle
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.3125
  lightness: 1
  brandColors:
    - '#99A4B3'
    - '#788799'
    - '#F2F3F2'
    - '#3A4A64'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: LesMarti Photography
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.09134
layout_spectrum: 0
